# DATA['objects']['IND_adm2']['geometries'][0]['properties']
MISSING = {
    "Arunachal Pradesh": {"Dibang Valley": "Upper Dibang Valley"},
    "Assam": {"Dima Hasao": "North Cachar Hills"},
    "Assam": {"Morigaon": "Marigaon"},
    # "Assam": {"Kamrup-metro": "Kamrup"},
    # "Assam": {"Kamrup-rural": "Kamrup"},
    "Assam": {"Dhubri": "Dhuburi"},
    "Bihar": {"Aurangabad (Bihar)":"Aurangabad"},
    "Bihar": {"Kaimur (Bhabua)":"Bhabua"},
    "Madhya Pradesh": {"Narsimhapur":"Narsinghpur"},
    "Madhya Pradesh": {"Khandwa":"East Nimar"},
    "Madhya Pradesh": {"Khargone":"West Nimar"},
    "Maharashtra": {"Aurangabad (Maharashtra)":"Aurangabad"},
    "Maharashtra": {"Ahmadnagar": "Ahmednagar"),
    #"Maharashtra": {"Mumbai (Suburban)":"Greater Bombay"},
    #"Maharashtra": {"Mumbai II":"Greater Bombay"},
    "Maharashtra": {"Gadchiroli":"Garhchiroli"},
    "Rajasthan": {"Jhunjhunu":"Jhunjhunun"},
    "Tamil Nadu": {"Tiruvallur": "Thiruvallur"},
    "Tamil Nadu": {"Tiruvarur": "Thiruvarur"},
    "Tamil Nadu": {"Sivagangai"; "Sivaganga"},
    "Tamil Nadu": {'Thoothukkudi':"Thoothukudi"},
    "Tamil Nadu": {"Tirunelveli":"Tirunelveli Kattabo"},
    "Tamil Nadu": {"Tiruchirappalli'":'Tiruchchirappalli'},
    "Tamil Nadu": {"The Nilgiris":"Nilgiris"},
    # "Andaman and Nicobar": {"Middle and North Andamans":"Andaman Islands"},
    # "Andaman and Nicobar": {"Andamans":"Andaman Islands"},
    "Andaman and Nicobar": {"Nicobars":"Nicobar Islands"},
    "Andhra Pradesh": {'Visakhapatnam':"Vishakhapatnam"},
    # "Andhra Pradesh": {"Warangal Rural":"Warangal"},
    # "Andhra Pradesh": {"Warangal Urban":"Warangal"},
    "Andhra Pradesh": {"Rangareddy":"Rangareddi"},
    "Andhra Pradesh": {"Mahabubnagar":"Mahbubnagar"},
    "Andhra Pradesh": {"Kadapa":"Cuddapah"},
    "Chhattisgarh": {"Janjgir - Champa":"Janjgir-Champa"},
    "Chhattisgarh": {"Baster":"Bastar"},
    "Chhattisgarh": {"Rajnandgaon":"Raj Nandgaon"},
    "Dadra and Nagar Haveli": {"Dadra and Nagar Haveli(UT)":"Dadra and Nagar Haveli"},
    "Delhi": {"New Delhi":"Delhi"},
    "Gujarat": {"Ahmedabad":"Ahmadabad"},
    "Gujarat": {"Dohad":"Dahod"},
    "Haryana": {"Yamunanagar": "Yamuna Nagar"},
    "Haryana": {"Sonipat":"Sonepat"},
    "Haryana": {"Gurugram":"Gurgaon"},
    "Himachal Pradesh": {"Lahul & Spiti":"Lahul and Spiti"},
    "Himachal Pradesh": {'Hamirpur (H.P.)':"Hamirapur"},
    "Jammu and Kashmir": {"Leh (Ladakh)":"Ladakh (Leh)"},
    "Jammu and Kashmir": {"Anantnag":"Anantnag (Kashmir South)"},
    "Jammu and Kashmir": {"Badgam":"Bagdam"},
    "Jammu and Kashmir": {"Baramula":"Baramula (Kashmir North)"},
    "Jammu and Kashmir": {"Kupwara ":"Kupwara (Muzaffarabad)"},
    "Jharkhand": {"Pakaur":"Pakur"},
    "Jharkhand": {'Kodarma':"Koderma"},
    "Jharkhand": {"Purbi Singhbhum":"Purba Singhbhum"},
    "Jharkhand": {"Pashchimi Singhbhum":"Pashchim Singhbhum"},
    "Jharkhand": {"Saraikela-Kharsawan":"Saraikela Kharsawan"},
    "Karnataka": {'Kalburgi':"Gulbarga"},
    #
    "Karnataka": {"Ballari":"Bellary"},
    "Karnataka": {'Belagavi':"Belgaum"},
    #"Karnataka": {"Uttara Kannanda":"Uttar Kannand"},
    #"Karnataka": {"Uttara Kannanda Sirsi":"Uttar Kannand"},
    "Karnataka": {'Shivamogga':"Shimoga"},
    "Karnataka": {'Tumakuru':"Tumkur"},
    #"Karnataka": {'Bengaluru U North':"Bangalore (Urban)"},
    #"Karnataka": {'Bengaluru U South':"Bangalore (Urban)"},
    #"Karnataka": {'Bengaluru Rural':"Bangalore (Urban)"},
    "Karnataka": {"Chamarajanagara":"Chamrajnagar"},
    "Karnataka": {"Mysuru":"Mysore"},
    "Karnataka": {"Dakshina Kannanda":"Dakshin Kannad"},
    "Karnataka": {"Chikkamangaluru":"Chikmagalur"},
    "Kerala": {"Pathanamthitta":"Pattanamtitta"},
    "Manipur": {"Imphal East":"East Imphal"},
    "Manipur": {"Imphal West":"West Imphal"},
    #"Meghalaya": {"East Jaintia Hills":"Jaintia Hills"},
    #"Meghalaya": {"West Jaintia Hills":"Jaintia Hills"},
    "Meghalaya": {"Ri Bhoi":"Ri-Bhoi"},
    "Orissa": {"Khurdha":"Khordha"},
    "Orissa": {"Balasore":"Baleshwar"},
    "Orissa": {"Sundergarh":"Sundargarh"},
    "Puducherry": {"Pondicherry":"Puducherry"},
    "Punjab": {"Nawanshahr":"Nawan Shehar"},
    "Uttar Pradesh": {"Jyotiba Phule Nagar (Amroha)":"Jyotiba Phule Nagar"},
    "Uttar Pradesh": {"Budaun":"Badaun"},
   #"Uttar Pradesh": {"Lakhimpur":"Lakhimpur Kheri"},
   #"Uttar Pradesh": {"Kheri":"Lakhimpur Kheri"},
    "Uttar Pradesh": {"Shrawasti":"Shravasti"},
    "Uttar Pradesh": {"Siddharthnagar":"Siddharth Nagar"},
    "Uttar Pradesh": {"Barabanki":"Bara Banki"},
    #"Uttar Pradesh": {"Kanpur Dehat":"Kanpur"},
    #"Uttar Pradesh": {"Kanpur Nagar":"Kanpur"},
    "Uttar Pradesh": {'Hamirpur (U.P.)'::"Hamirpur"},
    "Uttar Pradesh": {"Bhadoi":"Sant Ravi Das Nagar"},
    "Uttaranchal": {"Dehradun":"Dehra Dun}",
    "Uttaranchal": {"Hardwar":"Haridwar"},
    "Uttaranchal": {"Pauri":"Pauri Garhwal"},
    "Uttaranchal": {"Nainital":"Naini Tal"},
    "Uttaranchal": {"Rudraprayag":"Rudra Prayag"},
    "West Bengal": {"Darjeeling":"Darjiling"},
    "West Bengal": {"Cooch Bihar":"Kochbihar"},
    "West Bengal": {'Paschim Bardhaman':"Barddhaman"},
    "West Bengal": {"Hooghly":"Hugli"},
    "West Bengal": {"Purulia":"Puruliya"},
    "West Bengal": {'Paschim Medinipur':"West Midnapore"},
    "West Bengal": {'Purba Medinipur':"East Midnapore"},
    "West Bengal": {"Howrah":"Haora"},
}

NUM_SCHOOLS = [{'district': 'ANDAMANS', 'num_schools': 176},
 {'district': 'MIDDLE AND NORTH ANDAMANS', 'num_schools': 184},
 {'district': 'NICOBARS', 'num_schools': 58},
 {'district': 'ANANTAPUR', 'num_schools': 5226},
 {'district': 'CHITTOOR', 'num_schools': 6377},
 {'district': 'EAST GODAVARI', 'num_schools': 6290},
 {'district': 'GUNTUR', 'num_schools': 5090},
 {'district': 'KADAPA', 'num_schools': 4700},
 {'district': 'KRISHNA', 'num_schools': 4646},
 {'district': 'KURNOOL', 'num_schools': 4566},
 {'district': 'NELLORE', 'num_schools': 4646},
 {'district': 'PRAKASAM', 'num_schools': 4561},
 {'district': 'SRIKAKULAM', 'num_schools': 3977},
 {'district': 'VISAKHAPATNAM', 'num_schools': 5656},
 {'district': 'VIZIANAGARAM', 'num_schools': 3484},
 {'district': 'WEST GODAVARI', 'num_schools': 4605},
 {'district': 'ANJAW', 'num_schools': 91},
 {'district': 'CAPITAL COMPLEX ITANAGAR', 'num_schools': 142},
 {'district': 'CHANGLANG', 'num_schools': 346},
 {'district': 'DIBANG VALLEY', 'num_schools': 25},
 {'district': 'EAST KAMENG', 'num_schools': 192},
 {'district': 'EAST SIANG', 'num_schools': 162},
 {'district': 'KAMLE', 'num_schools': 126},
 {'district': 'KRA DADI', 'num_schools': 132},
 {'district': 'KURUNG KUMEY', 'num_schools': 121},
 {'district': 'LEPA RADA', 'num_schools': 63},
 {'district': 'LOHIT', 'num_schools': 105},
 {'district': 'LONGDING', 'num_schools': 107},
 {'district': 'LOWER DIBANG VALLEY', 'num_schools': 101},
 {'district': 'LOWER SIANG', 'num_schools': 82},
 {'district': 'LOWER SUBANSIRI', 'num_schools': 150},
 {'district': 'NAMSAI', 'num_schools': 221},
 {'district': 'PAKKE KESSANG', 'num_schools': 51},
 {'district': 'PAPUM PARE', 'num_schools': 264},
 {'district': 'SHI YOMI', 'num_schools': 44},
 {'district': 'SIANG', 'num_schools': 107},
 {'district': 'TAWANG', 'num_schools': 131},
 {'district': 'TIRAP', 'num_schools': 145},
 {'district': 'UPPER SIANG', 'num_schools': 126},
 {'district': 'UPPER SUBANSIRI', 'num_schools': 250},
 {'district': 'WEST KAMENG', 'num_schools': 236},
 {'district': 'WEST SIANG', 'num_schools': 146},
 {'district': 'BAKSA', 'num_schools': 2316},
 {'district': 'BARPETA', 'num_schools': 3444},
 {'district': 'BISWANATH', 'num_schools': 1481},
 {'district': 'BONGAIGAON', 'num_schools': 1502},
 {'district': 'CACHAR', 'num_schools': 3049},
 {'district': 'CHARAIDEO', 'num_schools': 904},
 {'district': 'CHIRANG', 'num_schools': 1254},
 {'district': 'DARRANG', 'num_schools': 1736},
 {'district': 'DHEMAJI', 'num_schools': 2186},
 {'district': 'DHUBRI', 'num_schools': 3432},
 {'district': 'DIBRUGARH', 'num_schools': 2106},
 {'district': 'DIMA HASAO', 'num_schools': 1074},
 {'district': 'GOALPARA', 'num_schools': 2458},
 {'district': 'GOLAGHAT', 'num_schools': 2024},
 {'district': 'HAILAKANDI', 'num_schools': 2788},
 {'district': 'HOJAI', 'num_schools': 1248},
 {'district': 'JORHAT', 'num_schools': 1783},
 {'district': 'KAMRUP-METRO', 'num_schools': 1122},
 {'district': 'KAMRUP-RURAL', 'num_schools': 3094},
 {'district': 'KARBI ANGLONG', 'num_schools': 1790},
 {'district': 'KARIMGANJ', 'num_schools': 2918},
 {'district': 'KOKRAJHAR', 'num_schools': 2634},
 {'district': 'LAKHIMPUR', 'num_schools': 3158},
 {'district': 'MAJULI', 'num_schools': 870},
 {'district': 'MORIGAON', 'num_schools': 1870},
 {'district': 'NAGAON', 'num_schools': 3171},
 {'district': 'NALBARI', 'num_schools': 1757},
 {'district': 'SIBSAGAR', 'num_schools': 1647},
 {'district': 'SONITPUR', 'num_schools': 1684},
 {'district': 'SOUTH SALMARA-MANKACHAR', 'num_schools': 843},
 {'district': 'TINSUKIA', 'num_schools': 1847},
 {'district': 'UDALGURI', 'num_schools': 1739},
 {'district': 'WEST KARBI ANGLONG', 'num_schools': 978},
 {'district': 'ARARIA', 'num_schools': 2592},
 {'district': 'ARWAL', 'num_schools': 731},
 {'district': 'AURANGABAD (BIHAR)', 'num_schools': 2552},
 {'district': 'BANKA', 'num_schools': 2415},
 {'district': 'BEGUSARAI', 'num_schools': 1996},
 {'district': 'BHAGALPUR', 'num_schools': 2305},
 {'district': 'BHOJPUR', 'num_schools': 2509},
 {'district': 'BUXAR', 'num_schools': 1583},
 {'district': 'DARBHANGA', 'num_schools': 3062},
 {'district': 'GAYA', 'num_schools': 4072},
 {'district': 'GOPALGANJ', 'num_schools': 2224},
 {'district': 'JAMUI', 'num_schools': 1938},
 {'district': 'JEHANABAD', 'num_schools': 1049},
 {'district': 'KAIMUR (BHABUA)', 'num_schools': 1427},
 {'district': 'KATIHAR', 'num_schools': 2563},
 {'district': 'KHAGARIA', 'num_schools': 1210},
 {'district': 'KISHANGANJ', 'num_schools': 1953},
 {'district': 'LAKHISARAI', 'num_schools': 995},
 {'district': 'MADHEPURA', 'num_schools': 1978},
 {'district': 'MADHUBANI', 'num_schools': 3681},
 {'district': 'MUNGER', 'num_schools': 1271},
 {'district': 'MUZAFFARPUR', 'num_schools': 3827},
 {'district': 'NALANDA', 'num_schools': 3043},
 {'district': 'NAWADA', 'num_schools': 2123},
 {'district': 'PASHCHIM CHAMPARAN', 'num_schools': 3431},
 {'district': 'PATNA', 'num_schools': 4553},
 {'district': 'PURBA CHAMPARAN', 'num_schools': 4042},
 {'district': 'PURNIA', 'num_schools': 2839},
 {'district': 'ROHTAS', 'num_schools': 2779},
 {'district': 'SAHARSA', 'num_schools': 1782},
 {'district': 'SAMASTIPUR', 'num_schools': 3159},
 {'district': 'SARAN', 'num_schools': 3152},
 {'district': 'SHEIKHPURA', 'num_schools': 619},
 {'district': 'SHEOHAR', 'num_schools': 473},
 {'district': 'SITAMARHI', 'num_schools': 2552},
 {'district': 'SIWAN', 'num_schools': 2990},
 {'district': 'SUPAUL', 'num_schools': 2145},
 {'district': 'VAISHALI', 'num_schools': 2660},
 {'district': 'CHANDIGARH', 'num_schools': 229},
 {'district': 'BALOD', 'num_schools': 1586},
 {'district': 'BALODABAZAR', 'num_schools': 2376},
 {'district': 'BALRAMPUR', 'num_schools': 2266},
 {'district': 'BASTER', 'num_schools': 2511},
 {'district': 'BEMETARA', 'num_schools': 1469},
 {'district': 'BIJAPUR', 'num_schools': 811},
 {'district': 'BILASPUR', 'num_schools': 3446},
 {'district': 'DANTEWADA', 'num_schools': 908},
 {'district': 'DHAMTARI', 'num_schools': 1727},
 {'district': 'DURG', 'num_schools': 1746},
 {'district': 'GARIABAND', 'num_schools': 1674},
 {'district': 'JANJGIR - CHAMPA', 'num_schools': 3265},
 {'district': 'JASHPUR', 'num_schools': 2650},
 {'district': 'KANKER', 'num_schools': 2606},
 {'district': 'KAWARDHA', 'num_schools': 1834},
 {'district': 'KONDAGAON', 'num_schools': 2080},
 {'district': 'KORBA', 'num_schools': 2501},
 {'district': 'KORIYA', 'num_schools': 1762},
 {'district': 'MAHASAMUND', 'num_schools': 2245},
 {'district': 'MUNGELI', 'num_schools': 1272},
 {'district': 'NARAYANPUR', 'num_schools': 603},
 {'district': 'RAIGARH', 'num_schools': 3551},
 {'district': 'RAIPUR', 'num_schools': 2430},
 {'district': 'RAJNANDGAON', 'num_schools': 3303},
 {'district': 'SUKMA', 'num_schools': 947},
 {'district': 'SURAJPUR', 'num_schools': 2381},
 {'district': 'SURGUJA', 'num_schools': 2353},
 {'district': 'DADRA AND NAGAR HAVELI(UT)', 'num_schools': 346},
 {'district': 'DAMAN', 'num_schools': 92},
 {'district': 'DIU', 'num_schools': 45},
 {'district': 'Central', 'num_schools': 227},
 {'district': 'East', 'num_schools': 581},
 {'district': 'New Delhi', 'num_schools': 90},
 {'district': 'North', 'num_schools': 331},
 {'district': 'North East', 'num_schools': 852},
 {'district': 'North West A', 'num_schools': 520},
 {'district': 'North West B', 'num_schools': 655},
 {'district': 'South', 'num_schools': 343},
 {'district': 'South East', 'num_schools': 509},
 {'district': 'South West A', 'num_schools': 205},
 {'district': 'South West B', 'num_schools': 546},
 {'district': 'West A', 'num_schools': 279},
 {'district': 'West B', 'num_schools': 531},
 {'district': 'NORTH GOA', 'num_schools': 686},
 {'district': 'SOUTH GOA', 'num_schools': 796},
 {'district': 'AHMEDABAD', 'num_schools': 4096},
 {'district': 'AMRELI', 'num_schools': 1295},
 {'district': 'ANAND', 'num_schools': 1664},
 {'district': 'ARAVALLI', 'num_schools': 1669},
 {'district': 'BANAS KANTHA', 'num_schools': 3372},
 {'district': 'BHARUCH', 'num_schools': 1456},
 {'district': 'BHAVNAGAR', 'num_schools': 1664},
 {'district': 'BOTAD', 'num_schools': 458},
 {'district': 'CHHOTAUDEPUR', 'num_schools': 1510},
 {'district': 'DEVBHOOMI DWARKA', 'num_schools': 943},
 {'district': 'DOHAD', 'num_schools': 2274},
 {'district': 'GANDHINAGAR', 'num_schools': 1443},
 {'district': 'GIR SOMNATH', 'num_schools': 1070},
 {'district': 'JAMNAGAR', 'num_schools': 1358},
 {'district': 'JUNAGADH', 'num_schools': 1580},
 {'district': 'KACHCHH', 'num_schools': 2516},
 {'district': 'KHEDA', 'num_schools': 1982},
 {'district': 'MAHESANA', 'num_schools': 1639},
 {'district': 'MAHISAGAR', 'num_schools': 1563},
 {'district': 'MORBI', 'num_schools': 966},
 {'district': 'NARMADA', 'num_schools': 904},
 {'district': 'NAVSARI', 'num_schools': 1104},
 {'district': 'PANCH MAHALS', 'num_schools': 1862},
 {'district': 'PATAN', 'num_schools': 1207},
 {'district': 'PORBANDAR', 'num_schools': 534},
 {'district': 'RAJKOT', 'num_schools': 2791},
 {'district': 'SABAR KANTHA', 'num_schools': 1803},
 {'district': 'SURAT', 'num_schools': 3278},
 {'district': 'SURENDRANAGAR', 'num_schools': 1452},
 {'district': 'TAPI', 'num_schools': 1052},
 {'district': 'THE DANGS', 'num_schools': 487},
 {'district': 'VADODARA', 'num_schools': 2127},
 {'district': 'VALSAD', 'num_schools': 1510},
 {'district': 'AMBALA', 'num_schools': 1092},
 {'district': 'BHIWANI', 'num_schools': 1170},
 {'district': 'CHARKHI DADRI', 'num_schools': 531},
 {'district': 'FARIDABAD', 'num_schools': 1537},
 {'district': 'FATEHABAD', 'num_schools': 894},
 {'district': 'GURUGRAM', 'num_schools': 1175},
 {'district': 'HISAR', 'num_schools': 1566},
 {'district': 'JHAJJAR', 'num_schools': 905},
 {'district': 'JIND', 'num_schools': 1115},
 {'district': 'KAITHAL', 'num_schools': 951},
 {'district': 'KARNAL', 'num_schools': 1325},
 {'district': 'KURUKSHETRA', 'num_schools': 1102},
 {'district': 'MAHENDRAGARH', 'num_schools': 1027},
 {'district': 'NUH', 'num_schools': 1066},
 {'district': 'PALWAL', 'num_schools': 1140},
 {'district': 'PANCHKULA', 'num_schools': 574},
 {'district': 'PANIPAT', 'num_schools': 991},
 {'district': 'REWARI', 'num_schools': 952},
 {'district': 'ROHTAK', 'num_schools': 807},
 {'district': 'SIRSA', 'num_schools': 1180},
 {'district': 'SONIPAT', 'num_schools': 1292},
 {'district': 'YAMUNANAGAR', 'num_schools': 1307},
 {'district': 'BILASPUR (H.P.)', 'num_schools': 1027},
 {'district': 'CHAMBA', 'num_schools': 1844},
 {'district': 'HAMIRPUR (H.P.)', 'num_schools': 972},
 {'district': 'KANGRA', 'num_schools': 3142},
 {'district': 'KINNAUR', 'num_schools': 304},
 {'district': 'KULLU', 'num_schools': 1224},
 {'district': 'LAHUL & SPITI', 'num_schools': 259},
 {'district': 'MANDI', 'num_schools': 2844},
 {'district': 'SHIMLA', 'num_schools': 2643},
 {'district': 'SIRMAUR', 'num_schools': 1636},
 {'district': 'SOLAN', 'num_schools': 1373},
 {'district': 'UNA', 'num_schools': 917},
 {'district': 'ANANTNAG', 'num_schools': 1980},
 {'district': 'BADGAM', 'num_schools': 1586},
 {'district': 'BANDIPORA', 'num_schools': 915},
 {'district': 'BARAMULA', 'num_schools': 2400},
 {'district': 'DODA', 'num_schools': 1504},
 {'district': 'GANDERBAL', 'num_schools': 712},
 {'district': 'JAMMU', 'num_schools': 2451},
 {'district': 'KATHUA', 'num_schools': 1807},
 {'district': 'KISHTWAR', 'num_schools': 934},
 {'district': 'KULGAM', 'num_schools': 1033},
 {'district': 'KUPWARA', 'num_schools': 2180},
 {'district': 'PULWAMA', 'num_schools': 1105},
 {'district': 'PUNCH', 'num_schools': 1763},
 {'district': 'RAJAURI', 'num_schools': 2073},
 {'district': 'RAMBAN', 'num_schools': 1000},
 {'district': 'REASI', 'num_schools': 1261},
 {'district': 'SAMBA', 'num_schools': 695},
 {'district': 'SHOPIAN', 'num_schools': 683},
 {'district': 'SRINAGAR', 'num_schools': 1007},
 {'district': 'UDHAMPUR', 'num_schools': 1774},
 {'district': 'BOKARO', 'num_schools': 2205},
 {'district': 'CHATRA', 'num_schools': 1865},
 {'district': 'DEOGHAR', 'num_schools': 2275},
 {'district': 'DHANBAD', 'num_schools': 2548},
 {'district': 'DUMKA', 'num_schools': 2611},
 {'district': 'GARHWA', 'num_schools': 1646},
 {'district': 'GIRIDIH', 'num_schools': 3932},
 {'district': 'GODDA', 'num_schools': 1778},
 {'district': 'GUMLA', 'num_schools': 1828},
 {'district': 'HAZARIBAG', 'num_schools': 2348},
 {'district': 'JAMTARA', 'num_schools': 1137},
 {'district': 'KHUNTI', 'num_schools': 1041},
 {'district': 'KODARMA', 'num_schools': 996},
 {'district': 'LATEHAR', 'num_schools': 1244},
 {'district': 'LOHARDAGA', 'num_schools': 705},
 {'district': 'PAKAUR', 'num_schools': 1195},
 {'district': 'PALAMU', 'num_schools': 2971},
 {'district': 'PASHCHIMI SINGHBHUM', 'num_schools': 2330},
 {'district': 'PURBI SINGHBHUM', 'num_schools': 2237},
 {'district': 'RAMGARH', 'num_schools': 973},
 {'district': 'RANCHI', 'num_schools': 3438},
 {'district': 'SAHIBGANJ', 'num_schools': 1558},
 {'district': 'SARAIKELA-KHARSAWAN', 'num_schools': 1612},
 {'district': 'SIMDEGA', 'num_schools': 1123},
 {'district': 'BAGALKOT', 'num_schools': 2384},
 {'district': 'BALLARI', 'num_schools': 3093},
 {'district': 'BELAGAVI', 'num_schools': 2426},
 {'district': 'BELAGAVI CHIKKODI', 'num_schools': 3138},
 {'district': 'BENGALURU RURAL', 'num_schools': 1525},
 {'district': 'BENGALURU U NORTH', 'num_schools': 2595},
 {'district': 'BENGALURU U SOUTH', 'num_schools': 3595},
 {'district': 'BIDAR', 'num_schools': 2845},
 {'district': 'CHAMARAJANAGARA', 'num_schools': 1214},
 {'district': 'CHIKKABALLAPURA', 'num_schools': 2099},
 {'district': 'CHIKKAMANGALURU', 'num_schools': 1945},
 {'district': 'CHITRADURGA', 'num_schools': 2491},
 {'district': 'DAKSHINA KANNADA', 'num_schools': 2034},
 {'district': 'DAVANAGERE', 'num_schools': 2125},
 {'district': 'DHARWAD', 'num_schools': 1683},
 {'district': 'GADAG', 'num_schools': 1221},
 {'district': 'HASSAN', 'num_schools': 3236},
 {'district': 'HAVERI', 'num_schools': 2012},
 {'district': 'KALBURGI', 'num_schools': 4079},
 {'district': 'KODAGU', 'num_schools': 658},
 {'district': 'KOLAR', 'num_schools': 2521},
 {'district': 'KOPPAL', 'num_schools': 1726},
 {'district': 'MANDYA', 'num_schools': 2469},
 {'district': 'MYSURU', 'num_schools': 3306},
 {'district': 'RAICHUR', 'num_schools': 2551},
 {'district': 'RAMANAGARA', 'num_schools': 1774},
 {'district': 'SHIVAMOGGA', 'num_schools': 2803},
 {'district': 'TUMAKURU', 'num_schools': 2961},
 {'district': 'TUMAKURU MADHUGIRI', 'num_schools': 1692},
 {'district': 'UDUPI', 'num_schools': 1185},
 {'district': 'UTTARA KANNADA', 'num_schools': 1253},
 {'district': 'UTTARA KANNADA SIRSI', 'num_schools': 1389},
 {'district': 'VIJAYAPURA', 'num_schools': 3541},
 {'district': 'YADAGIRI', 'num_schools': 1597},
 {'district': 'ALAPPUZHA', 'num_schools': 1010},
 {'district': 'ERNAKULAM', 'num_schools': 1373},
 {'district': 'IDUKKI', 'num_schools': 687},
 {'district': 'KANNUR', 'num_schools': 1608},
 {'district': 'KASARAGOD', 'num_schools': 778},
 {'district': 'KOLLAM', 'num_schools': 1251},
 {'district': 'KOTTAYAM', 'num_schools': 1135},
 {'district': 'KOZHIKODE', 'num_schools': 1598},
 {'district': 'MALAPPURAM', 'num_schools': 1926},
 {'district': 'PALAKKAD', 'num_schools': 1273},
 {'district': 'PATHANAMTHITTA', 'num_schools': 912},
 {'district': 'THIRUVANANTHAPURAM', 'num_schools': 1429},
 {'district': 'THRISSUR', 'num_schools': 1268},
 {'district': 'WAYANAD', 'num_schools': 417},
 {'district': 'KARGIL', 'num_schools': 618},
 {'district': 'LEH (LADAKH)', 'num_schools': 436},
 {'district': 'LAKSHADWEEP', 'num_schools': 45},
 {'district': 'AGAR MALWA', 'num_schools': 1185},
 {'district': 'ALIRAJPUR', 'num_schools': 2559},
 {'district': 'ANUPPUR', 'num_schools': 1921},
 {'district': 'ASHOKNAGAR', 'num_schools': 1597},
 {'district': 'BALAGHAT', 'num_schools': 3085},
 {'district': 'BARWANI', 'num_schools': 3538},
 {'district': 'BETUL', 'num_schools': 3143},
 {'district': 'BHIND', 'num_schools': 2896},
 {'district': 'BHOPAL', 'num_schools': 2946},
 {'district': 'BURHANPUR', 'num_schools': 898},
 {'district': 'CHHATARPUR', 'num_schools': 3179},
 {'district': 'CHHINDWARA', 'num_schools': 4057},
 {'district': 'DAMOH', 'num_schools': 2183},
 {'district': 'DATIA', 'num_schools': 1388},
 {'district': 'DEWAS', 'num_schools': 2823},
 {'district': 'DHAR', 'num_schools': 5077},
 {'district': 'DINDORI', 'num_schools': 2093},
 {'district': 'GUNA', 'num_schools': 2526},
 {'district': 'GWALIOR', 'num_schools': 3002},
 {'district': 'HARDA', 'num_schools': 965},
 {'district': 'HOSHANGABAD', 'num_schools': 1955},
 {'district': 'INDORE', 'num_schools': 3731},
 {'district': 'JABALPUR', 'num_schools': 2902},
 {'district': 'JHABUA', 'num_schools': 2825},
 {'district': 'KATNI', 'num_schools': 2067},
 {'district': 'KHANDWA', 'num_schools': 1929},
 {'district': 'KHARGONE', 'num_schools': 4044},
 {'district': 'MANDLA', 'num_schools': 3067},
 {'district': 'MANDSAUR', 'num_schools': 2472},
 {'district': 'MORENA', 'num_schools': 3433},
 {'district': 'NARSIMHAPUR', 'num_schools': 1843},
 {'district': 'NEEMUCH', 'num_schools': 1410},
 {'district': 'NIWARI', 'num_schools': 664},
 {'district': 'PANNA', 'num_schools': 2272},
 {'district': 'RAISEN', 'num_schools': 2596},
 {'district': 'RAJGARH', 'num_schools': 2920},
 {'district': 'RATLAM', 'num_schools': 2610},
 {'district': 'REWA', 'num_schools': 4461},
 {'district': 'SAGAR', 'num_schools': 3543},
 {'district': 'SATNA', 'num_schools': 4005},
 {'district': 'SEHORE', 'num_schools': 2354},
 {'district': 'SEONI', 'num_schools': 3215},
 {'district': 'SHAHDOL', 'num_schools': 2520},
 {'district': 'SHAJAPUR', 'num_schools': 1765},
 {'district': 'SHEOPUR', 'num_schools': 1396},
 {'district': 'SHIVPURI', 'num_schools': 3339},
 {'district': 'SIDHI', 'num_schools': 2378},
 {'district': 'SINGRAULI', 'num_schools': 2088},
 {'district': 'TIKAMGARH', 'num_schools': 1710},
 {'district': 'UJJAIN', 'num_schools': 2973},
 {'district': 'UMARIA', 'num_schools': 1147},
 {'district': 'VIDISHA', 'num_schools': 2684},
 {'district': 'AHMADNAGAR', 'num_schools': 5376},
 {'district': 'AKOLA', 'num_schools': 1868},
 {'district': 'AMRAVATI', 'num_schools': 2898},
 {'district': 'AURANGABAD (MAHARASHTRA)', 'num_schools': 4555},
 {'district': 'BHANDARA', 'num_schools': 1323},
 {'district': 'BID', 'num_schools': 3686},
 {'district': 'BULDANA', 'num_schools': 2475},
 {'district': 'CHANDRAPUR', 'num_schools': 2507},
 {'district': 'DHULE', 'num_schools': 2015},
 {'district': 'GADCHIROLI', 'num_schools': 2045},
 {'district': 'GONDIYA', 'num_schools': 1664},
 {'district': 'HINGOLI', 'num_schools': 1325},
 {'district': 'JALGAON', 'num_schools': 3399},
 {'district': 'JALNA', 'num_schools': 2437},
 {'district': 'KOLHAPUR', 'num_schools': 3712},
 {'district': 'LATUR', 'num_schools': 2715},
 {'district': 'MUMBAI (SUBURBAN)', 'num_schools': 2541},
 {'district': 'MUMBAI II', 'num_schools': 1802},
 {'district': 'NAGPUR', 'num_schools': 4142},
 {'district': 'NANDED', 'num_schools': 3731},
 {'district': 'NANDURBAR', 'num_schools': 2067},
 {'district': 'NASHIK', 'num_schools': 5626},
 {'district': 'OSMANABAD', 'num_schools': 1843},
 {'district': 'PALGHAR', 'num_schools': 3448},
 {'district': 'PARBHANI', 'num_schools': 2107},
 {'district': 'PUNE', 'num_schools': 7455},
 {'district': 'RAIGARH (MAHARASHTRA)', 'num_schools': 3711},
 {'district': 'RATNAGIRI', 'num_schools': 3202},
 {'district': 'SANGLI', 'num_schools': 2977},
 {'district': 'SATARA', 'num_schools': 3879},
 {'district': 'SINDHUDURG', 'num_schools': 1711},
 {'district': 'SOLAPUR', 'num_schools': 4788},
 {'district': 'THANE', 'num_schools': 4958},
 {'district': 'WARDHA', 'num_schools': 1509},
 {'district': 'WASHIM', 'num_schools': 1379},
 {'district': 'YAVATMAL', 'num_schools': 3353},
 {'district': 'BISHNUPUR', 'num_schools': 311},
 {'district': 'CHANDEL', 'num_schools': 231},
 {'district': 'CHURACHANDPUR', 'num_schools': 465},
 {'district': 'IMPHAL EAST', 'num_schools': 515},
 {'district': 'IMPHAL WEST', 'num_schools': 549},
 {'district': 'JIRIBAM', 'num_schools': 109},
 {'district': 'KAKCHING', 'num_schools': 171},
 {'district': 'KAMJONG', 'num_schools': 140},
 {'district': 'KANGPOKPI', 'num_schools': 529},
 {'district': 'NONEY', 'num_schools': 139},
 {'district': 'PHERZAWL', 'num_schools': 128},
 {'district': 'SENAPATI', 'num_schools': 355},
 {'district': 'TAMENGLONG', 'num_schools': 273},
 {'district': 'TENGNOUPAL', 'num_schools': 159},
 {'district': 'THOUBAL', 'num_schools': 364},
 {'district': 'UKHRUL', 'num_schools': 225},
 {'district': 'EAST GARO HILLS', 'num_schools': 726},
 {'district': 'EAST JAINTIA HILLS', 'num_schools': 703},
 {'district': 'EAST KHASI HILLS', 'num_schools': 2910},
 {'district': 'NORTH GARO HILLS', 'num_schools': 873},
 {'district': 'RI BHOI', 'num_schools': 1263},
 {'district': 'SOUTH GARO HILLS', 'num_schools': 1067},
 {'district': 'SOUTH WEST GARO HILLS', 'num_schools': 782},
 {'district': 'SOUTH WEST KHASI HILLS', 'num_schools': 992},
 {'district': 'WEST GARO HILLS', 'num_schools': 2368},
 {'district': 'WEST JAINTIA HILLS', 'num_schools': 1228},
 {'district': 'WEST KHASI HILLS', 'num_schools': 1818},
 {'district': 'AIZAWL', 'num_schools': 1012},
 {'district': 'CHAMPHAI', 'num_schools': 456},
 {'district': 'KOLASIB', 'num_schools': 282},
 {'district': 'LAWNGTLAI', 'num_schools': 563},
 {'district': 'LUNGLEI', 'num_schools': 740},
 {'district': 'MAMIT', 'num_schools': 385},
 {'district': 'SAIHA', 'num_schools': 259},
 {'district': 'SERCHHIP', 'num_schools': 227},
 {'district': 'DIMAPUR', 'num_schools': 517},
 {'district': 'KIPHIRE', 'num_schools': 136},
 {'district': 'KOHIMA', 'num_schools': 281},
 {'district': 'LONGLENG', 'num_schools': 111},
 {'district': 'MOKOKCHUNG', 'num_schools': 259},
 {'district': 'MON', 'num_schools': 308},
 {'district': 'PEREN', 'num_schools': 170},
 {'district': 'PHEK', 'num_schools': 245},
 {'district': 'TUENSANG', 'num_schools': 257},
 {'district': 'WOKHA', 'num_schools': 192},
 {'district': 'ZUNHEBOTO', 'num_schools': 282},
 {'district': 'ANGUL', 'num_schools': 1943},
 {'district': 'BALASORE', 'num_schools': 3508},
 {'district': 'BARAGARH', 'num_schools': 2095},
 {'district': 'BHADRAK', 'num_schools': 2262},
 {'district': 'BOLANGIR', 'num_schools': 2668},
 {'district': 'BOUDH', 'num_schools': 913},
 {'district': 'CUTTACK', 'num_schools': 3064},
 {'district': 'DEOGARH', 'num_schools': 672},
 {'district': 'DHENKANAL', 'num_schools': 1839},
 {'district': 'GAJAPATI', 'num_schools': 1257},
 {'district': 'GANJAM', 'num_schools': 4344},
 {'district': 'JAGATSINGHPUR', 'num_schools': 1755},
 {'district': 'JAJPUR', 'num_schools': 2899},
 {'district': 'JHARSUGUDA', 'num_schools': 828},
 {'district': 'KALAHANDI', 'num_schools': 2742},
 {'district': 'KANDHAMAL', 'num_schools': 2013},
 {'district': 'KENDRAPARA', 'num_schools': 2341},
 {'district': 'KEONJHAR', 'num_schools': 3287},
 {'district': 'KHURDHA', 'num_schools': 2306},
 {'district': 'KORAPUT', 'num_schools': 2725},
 {'district': 'MALKANGIRI', 'num_schools': 1413},
 {'district': 'MAYURBHANJ', 'num_schools': 4937},
 {'district': 'NABARANGPUR', 'num_schools': 2082},
 {'district': 'NAYAGARH', 'num_schools': 1449},
 {'district': 'NUAPADA', 'num_schools': 1198},
 {'district': 'PURI', 'num_schools': 2557},
 {'district': 'RAYAGADA', 'num_schools': 2076},
 {'district': 'SAMBALPUR', 'num_schools': 1690},
 {'district': 'SONEPUR', 'num_schools': 1101},
 {'district': 'SUNDERGARH', 'num_schools': 3056},
 {'district': 'KARAIKAL', 'num_schools': 168},
 {'district': 'MAHE', 'num_schools': 33},
 {'district': 'PONDICHERRY', 'num_schools': 503},
 {'district': 'YANAM', 'num_schools': 37},
 {'district': 'AMRITSAR', 'num_schools': 2236},
 {'district': 'BARNALA', 'num_schools': 469},
 {'district': 'BATHINDA', 'num_schools': 1067},
 {'district': 'FARIDKOT', 'num_schools': 557},
 {'district': 'FATEHGARH SAHIB', 'num_schools': 824},
 {'district': 'FIROZPUR', 'num_schools': 1100},
 {'district': 'Fazilka', 'num_schools': 1060},
 {'district': 'GURDASPUR', 'num_schools': 2154},
 {'district': 'HOSHIARPUR', 'num_schools': 2274},
 {'district': 'JALANDHAR', 'num_schools': 2237},
 {'district': 'KAPURTHALA', 'num_schools': 1063},
 {'district': 'LUDHIANA', 'num_schools': 2998},
 {'district': 'MANSA', 'num_schools': 689},
 {'district': 'MOGA', 'num_schools': 856},
 {'district': 'MOHALI', 'num_schools': 1055},
 {'district': 'MUKTSAR', 'num_schools': 789},
 {'district': 'NAWANSHAHR', 'num_schools': 826},
 {'district': 'PATHANKOT', 'num_schools': 798},
 {'district': 'PATIALA', 'num_schools': 2000},
 {'district': 'RUPNAGAR', 'num_schools': 1006},
 {'district': 'SANGRUR', 'num_schools': 1563},
 {'district': 'TARAN TARAN', 'num_schools': 1154},
 {'district': 'AJMER', 'num_schools': 3337},
 {'district': 'ALWAR', 'num_schools': 5219},
 {'district': 'BANSWARA', 'num_schools': 3820},
 {'district': 'BARAN', 'num_schools': 2202},
 {'district': 'BARMER', 'num_schools': 5662},
 {'district': 'BHARATPUR', 'num_schools': 3218},
 {'district': 'BHILWARA', 'num_schools': 4058},
 {'district': 'BIKANER', 'num_schools': 3457},
 {'district': 'BUNDI', 'num_schools': 1868},
 {'district': 'CHITTAURGARH', 'num_schools': 2597},
 {'district': 'CHURU', 'num_schools': 2578},
 {'district': 'DAUSA', 'num_schools': 2574},
 {'district': 'DHAULPUR', 'num_schools': 1831},
 {'district': 'DUNGARPUR', 'num_schools': 3122},
 {'district': 'GANGANAGAR', 'num_schools': 3026},
 {'district': 'HANUMANGARH', 'num_schools': 2057},
 {'district': 'JAIPUR', 'num_schools': 9112},
 {'district': 'JAISALMER', 'num_schools': 1622},
 {'district': 'JALOR', 'num_schools': 2732},
 {'district': 'JHALAWAR', 'num_schools': 2251},
 {'district': 'JHUNJHUNU', 'num_schools': 2781},
 {'district': 'JODHPUR', 'num_schools': 5776},
 {'district': 'KARAULI', 'num_schools': 2171},
 {'district': 'KOTA', 'num_schools': 2329},
 {'district': 'NAGAUR', 'num_schools': 4839},
 {'district': 'PALI', 'num_schools': 2931},
 {'district': 'PRATAPGARH (RAJ.)', 'num_schools': 2007},
 {'district': 'RAJSAMAND', 'num_schools': 2233},
 {'district': 'SAWAI MADHOPUR', 'num_schools': 1975},
 {'district': 'SIKAR', 'num_schools': 3530},
 {'district': 'SIROHI', 'num_schools': 1414},
 {'district': 'TONK', 'num_schools': 2478},
 {'district': 'UDAIPUR', 'num_schools': 5433},
 {'district': 'EAST SIKKIM', 'num_schools': 445},
 {'district': 'NORTH SIKKIM', 'num_schools': 111},
 {'district': 'SOUTH SIKKIM', 'num_schools': 370},
 {'district': 'WEST SIKKIM', 'num_schools': 351},
 {'district': 'ARIYALUR', 'num_schools': 783},
 {'district': 'CHENNAI', 'num_schools': 1466},
 {'district': 'COIMBATORE', 'num_schools': 2046},
 {'district': 'CUDDALORE', 'num_schools': 2223},
 {'district': 'DHARMAPURI', 'num_schools': 1625},
 {'district': 'DINDIGUL', 'num_schools': 1976},
 {'district': 'ERODE', 'num_schools': 1763},
 {'district': 'KANCHEEPURAM', 'num_schools': 2610},
 {'district': 'KANNIYAKUMARI', 'num_schools': 1229},
 {'district': 'KARUR', 'num_schools': 1060},
 {'district': 'KRISHNAGIRI', 'num_schools': 2054},
 {'district': 'MADURAI', 'num_schools': 2250},
 {'district': 'NAGAPATTINAM', 'num_schools': 1540},
 {'district': 'NAMAKKAL', 'num_schools': 1371},
 {'district': 'PERAMBALUR', 'num_schools': 519},
 {'district': 'PUDUKKOTTAI', 'num_schools': 1958},
 {'district': 'RAMANATHAPURAM', 'num_schools': 1529},
 {'district': 'SALEM', 'num_schools': 2454},
 {'district': 'SIVAGANGAI', 'num_schools': 1606},
 {'district': 'THANJAVUR', 'num_schools': 2062},
 {'district': 'THE NILGIRIS', 'num_schools': 708},
 {'district': 'THENI', 'num_schools': 940},
 {'district': 'THOOTHUKKUDI', 'num_schools': 1864},
 {'district': 'TIRUCHIRAPPALLI', 'num_schools': 2109},
 {'district': 'TIRUNELVELI', 'num_schools': 2830},
 {'district': 'TIRUPPUR', 'num_schools': 1919},
 {'district': 'TIRUVALLUR', 'num_schools': 2535},
 {'district': 'TIRUVANNAMALAI', 'num_schools': 2536},
 {'district': 'TIRUVARUR', 'num_schools': 1280},
 {'district': 'VELLORE', 'num_schools': 3338},
 {'district': 'VILLUPURAM', 'num_schools': 2978},
 {'district': 'VIRUDHUNAGAR', 'num_schools': 1736},
 {'district': 'ADILABAD', 'num_schools': 1456},
 {'district': 'BHADRADRI', 'num_schools': 1722},
 {'district': 'HYDERABAD', 'num_schools': 3138},
 {'district': 'JAGTIAL', 'num_schools': 1179},
 {'district': 'JANGAON', 'num_schools': 666},
 {'district': 'JAYASHANKAR', 'num_schools': 550},
 {'district': 'JOGULAMBA', 'num_schools': 632},
 {'district': 'KAMAREDDY', 'num_schools': 1292},
 {'district': 'KARIMNAGAR', 'num_schools': 1064},
 {'district': 'KHAMMAM', 'num_schools': 1696},
 {'district': 'KOMARAM BHEEM', 'num_schools': 1279},
 {'district': 'MAHABUBABAD', 'num_schools': 1237},
 {'district': 'MAHABUBNAGAR', 'num_schools': 1225},
 {'district': 'MANCHERIAL', 'num_schools': 1088},
 {'district': 'MEDAK', 'num_schools': 1091},
 {'district': 'MEDCHAL', 'num_schools': 2025},
 {'district': 'MULUGU', 'num_schools': 569},
 {'district': 'NAGARKURNOOL', 'num_schools': 1152},
 {'district': 'NALGONDA', 'num_schools': 2105},
 {'district': 'NARAYANAPET', 'num_schools': 679},
 {'district': 'NIRMAL', 'num_schools': 1071},
 {'district': 'NIZAMABAD', 'num_schools': 1809},
 {'district': 'PEDDAPALLI', 'num_schools': 792},
 {'district': 'RAJANNA', 'num_schools': 677},
 {'district': 'RANGAREDDY', 'num_schools': 2898},
 {'district': 'SANGAREDDY', 'num_schools': 1818},
 {'district': 'SIDDIPET', 'num_schools': 1317},
 {'district': 'SURYAPET', 'num_schools': 1317},
 {'district': 'VIKARABAD', 'num_schools': 1326},
 {'district': 'WANAPARTHY', 'num_schools': 743},
 {'district': 'WARANGAL RURAL', 'num_schools': 890},
 {'district': 'WARANGAL URBAN', 'num_schools': 1112},
 {'district': 'YADADRI', 'num_schools': 960},
 {'district': 'DHALAI', 'num_schools': 885},
 {'district': 'GOMATI', 'num_schools': 612},
 {'district': 'KHOWAI', 'num_schools': 496},
 {'district': 'NORTH TRIPURA', 'num_schools': 533},
 {'district': 'SEPAHIJALA', 'num_schools': 657},
 {'district': 'SOUTH TRIPURA', 'num_schools': 671},
 {'district': 'UNAKOTI', 'num_schools': 379},
 {'district': 'WEST TRIPURA', 'num_schools': 707},
 {'district': 'AGRA', 'num_schools': 5112},
 {'district': 'ALIGARH', 'num_schools': 4264},
 {'district': 'ALLAHABAD', 'num_schools': 5695},
 {'district': 'AMBEDKAR NAGAR', 'num_schools': 3859},
 {'district': 'AMETHI - CSM NAGAR', 'num_schools': 2483},
 {'district': 'AURAIYA', 'num_schools': 2377},
 {'district': 'AZAMGARH', 'num_schools': 5998},
 {'district': 'BAGHPAT', 'num_schools': 1083},
 {'district': 'BAHRAICH', 'num_schools': 4035},
 {'district': 'BALLIA', 'num_schools': 3823},
 {'district': 'BALRAMPUR', 'num_schools': 2885},
 {'district': 'BANDA', 'num_schools': 2379},
 {'district': 'BARABANKI', 'num_schools': 4112},
 {'district': 'BAREILLY', 'num_schools': 4779},
 {'district': 'BASTI', 'num_schools': 3543},
 {'district': 'BHADOI', 'num_schools': 1836},
 {'district': 'BIJNOR', 'num_schools': 5071},
 {'district': 'BUDAUN', 'num_schools': 3550},
 {'district': 'BULANDSHAHR', 'num_schools': 3783},
 {'district': 'CHANDAULI', 'num_schools': 2086},
 {'district': 'CHITRAKOOT', 'num_schools': 1723},
 {'district': 'DEORIA', 'num_schools': 4108},
 {'district': 'ETAH', 'num_schools': 3328},
 {'district': 'ETAWAH', 'num_schools': 3216},
 {'district': 'FAIZABAD', 'num_schools': 3724},
 {'district': 'FARRUKHABAD', 'num_schools': 2802},
 {'district': 'FATEHPUR', 'num_schools': 3719},
 {'district': 'FIROZABAD', 'num_schools': 3629},
 {'district': 'GAUTAM BUDDHA NAGAR', 'num_schools': 1573},
 {'district': 'GHAZIABAD', 'num_schools': 2151},
 {'district': 'GHAZIPUR', 'num_schools': 5918},
 {'district': 'GONDA', 'num_schools': 4590},
 {'district': 'GORAKHPUR', 'num_schools': 4580},
 {'district': 'HAMIRPUR (U.P.)', 'num_schools': 1781},
 {'district': 'HAPUR (PANCHSHEEL NAGAR)', 'num_schools': 1169},
 {'district': 'HARDOI', 'num_schools': 5465},
 {'district': 'HATHRAS', 'num_schools': 2297},
 {'district': 'JALAUN', 'num_schools': 2625},
 {'district': 'JAUNPUR', 'num_schools': 6028},
 {'district': 'JHANSI', 'num_schools': 2667},
 {'district': 'Jyotiba Phule Nagar (AMROHA)', 'num_schools': 3216},
 {'district': 'KANNAUJ', 'num_schools': 2718},
 {'district': 'KANPUR DEHAT', 'num_schools': 2670},
 {'district': 'KANPUR NAGAR', 'num_schools': 4687},
 {'district': 'KANSHIRAM NAGAR', 'num_schools': 2381},
 {'district': 'KAUSHAMBI', 'num_schools': 2171},
 {'district': 'KHERI', 'num_schools': 4551},
 {'district': 'KUSHINAGAR', 'num_schools': 4562},
 {'district': 'LALITPUR', 'num_schools': 1963},
 {'district': 'LUCKNOW', 'num_schools': 4143},
 {'district': 'MAHARAJGANJ', 'num_schools': 3244},
 {'district': 'MAHOBA', 'num_schools': 1436},
 {'district': 'MAINPURI', 'num_schools': 3562},
 {'district': 'MATHURA', 'num_schools': 3050},
 {'district': 'MAU', 'num_schools': 2840},
 {'district': 'MEERUT', 'num_schools': 3042},
 {'district': 'MIRZAPUR', 'num_schools': 3306},
 {'district': 'MORADABAD', 'num_schools': 4381},
 {'district': 'MUZAFFARNAGAR', 'num_schools': 2854},
 {'district': 'PILIBHIT', 'num_schools': 2533},
 {'district': 'PRATAPGARH', 'num_schools': 4874},
 {'district': 'RAE BARELI', 'num_schools': 3452},
 {'district': 'RAMPUR', 'num_schools': 3150},
 {'district': 'SAHARANPUR', 'num_schools': 4362},
 {'district': 'SAMBHAL (BHIM NAGAR)', 'num_schools': 2421},
 {'district': 'SANT KABIR NAGAR', 'num_schools': 2281},
 {'district': 'SHAHJAHANPUR', 'num_schools': 4324},
 {'district': 'SHAMLI (PRABUDH NAGAR)', 'num_schools': 1407},
 {'district': 'SHRAWASTI', 'num_schools': 1487},
 {'district': 'SIDDHARTHNAGAR', 'num_schools': 3442},
 {'district': 'SITAPUR', 'num_schools': 5850},
 {'district': 'SONBHADRA', 'num_schools': 2788},
 {'district': 'SULTANPUR', 'num_schools': 3556},
 {'district': 'UNNAO', 'num_schools': 4438},
 {'district': 'VARANASI', 'num_schools': 3364},
 {'district': 'ALMORA', 'num_schools': 2058},
 {'district': 'BAGESHWAR', 'num_schools': 909},
 {'district': 'CHAMOLI', 'num_schools': 1581},
 {'district': 'CHAMPAWAT', 'num_schools': 815},
 {'district': 'DEHRADUN', 'num_schools': 2543},
 {'district': 'HARDWAR', 'num_schools': 2260},
 {'district': 'NAINITAL', 'num_schools': 1938},
 {'district': 'PAURI', 'num_schools': 2470},
 {'district': 'PITHORAGARH', 'num_schools': 1785},
 {'district': 'RUDRAPRAYAG', 'num_schools': 966},
 {'district': 'TEHRI GARHWAL', 'num_schools': 2290},
 {'district': 'UDHAM SINGH NAGAR', 'num_schools': 2299},
 {'district': 'UTTARKASHI', 'num_schools': 1381},
 {'district': 'ALIPURDUAR', 'num_schools': 2020},
 {'district': 'BANKURA', 'num_schools': 5251},
 {'district': 'BIRBHUM', 'num_schools': 4235},
 {'district': 'COOCH BIHAR', 'num_schools': 3607},
 {'district': 'DAKSHIN DINAJPUR', 'num_schools': 2333},
 {'district': 'DARJEELING', 'num_schools': 1266},
 {'district': 'HOOGHLY', 'num_schools': 4680},
 {'district': 'HOWRAH', 'num_schools': 3691},
 {'district': 'JALPAIGURI', 'num_schools': 2748},
 {'district': 'JHARGRAM', 'num_schools': 2498},
 {'district': 'KALIMPONG', 'num_schools': 542},
 {'district': 'KOLKATA', 'num_schools': 2421},
 {'district': 'MALDAH', 'num_schools': 4596},
 {'district': 'MURSHIDABAD', 'num_schools': 7160},
 {'district': 'NADIA', 'num_schools': 4563},
 {'district': 'NORTH 24 PARGANAS', 'num_schools': 6563},
 {'district': 'PASCHIM BARDHAMAN', 'num_schools': 1994},
 {'district': 'PASCHIM MEDINIPUR', 'num_schools': 7088},
 {'district': 'PURBA BARDHAMAN', 'num_schools': 5097},
 {'district': 'PURBA MEDINIPUR', 'num_schools': 6738},
 {'district': 'PURULIA', 'num_schools': 4842},
 {'district': 'SILIGURI', 'num_schools': 1139},
 {'district': 'SOUTH 24 PARGANAS', 'num_schools': 7397},
 {'district': 'UTTAR DINAJPUR', 'num_schools': 3286}]
